# Generated by Django 3.0.1 on 2020-01-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=15)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
